PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Models/AuthDetails.cs
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// ----------------------------------------------------------------------------

namespace UserOwnsData.Models
{
	public class AuthDetails
	{
		public string UserName { get; set; }
		public string AccessToken { get; set; }
	}
}

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Models/ErrorModel.cs
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// ----------------------------------------------------------------------------

namespace UserOwnsData.Models
{
	using System.Net;

	public class ErrorModel
	{
		public HttpStatusCode ErrorCode { get; set; }
		public string ErrorMessage { get; set; }
	}
}

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Controllers/EmbedInfoController.cs
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// ----------------------------------------------------------------------------

namespace UserOwnsData.Controllers
{
	using System;
	using System.Net;
	using System.Security.Claims;
	using System.Web.Mvc;
	using UserOwnsData.Models;
	using UserOwnsData.Services;
	using UserOwnsData.Services.Security;

	public class EmbedInfoController : Controller
	{
		/// <summary>
		/// Returns Embed view when client is authorized
		/// </summary>
		/// <returns>Returns Embed view with authentication details</returns>
		[Authorize]
		public ActionResult Embed()
		{
			try
			{
				var userName = ClaimsPrincipal.Current.FindFirst("name").Value;

				var accessToken = TokenManager.GetAccessToken(PowerBIPermissionScopes.ReadUserWorkspaces);

				AuthDetails authDetails = new AuthDetails
				{
					UserName = userName,
					AccessToken = accessToken
				};

				return View("embed", authDetails);
			}
			catch (Exception ex)
			{
				ErrorModel errorModel = Utils.GetErrorModel((HttpStatusCode)500, ex.ToString());
				return View("Error", errorModel);
			}
		}
	}
}

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Controllers/HomeController.cs
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// ----------------------------------------------------------------------------

namespace UserOwnsData.Controllers
{
	using System.Net;
	using System.Web.Mvc;
	using UserOwnsData.Models;
	using UserOwnsData.Services;

	public class HomeController : Controller
	{
		/// <summary>
		/// Returns Index view to the client after validating app configurations
		/// </summary>
		/// <returns>Returns Index view</returns>
		public ActionResult Index()
		{
			// Validate sanctity of configuration before proceeding
			string configValidationResult = ConfigValidatorService.ValidateConfig();
			if (configValidationResult != null)
			{
				ErrorModel errorModel = Utils.GetErrorModel((HttpStatusCode)400, configValidationResult);
				return View("Error", errorModel);
			}
			return View();
		}
	}
}

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Views/Home/Index.cshtml
@* Copyright (c) Microsoft Corporation.
Licensed under the MIT license. *@

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	window.onload = function () {
		// Sign-in button click event
		$(".sign-in").on("click", function () {
			location.href = '@Url.Action("Embed", "EmbedInfo")';
		});
	};
</script>

<div class="sign-in-div">
	<div class="signin-container">
		<p>Sign in to Power BI</p>
		<button class="sign-in">Sign in</button>
	</div>
</div>

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Views/Shared/Embed.cshtml
@* Copyright (c) Microsoft Corporation.
    Licensed under the MIT license. *@

@model UserOwnsData.Models.AuthDetails

@{
    ViewBag.Title = "Embed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="outer-div">
    <header class="row">
        <div class="heading col-lg-6 col-md-6">Power BI Embedded Sample</div>
        <div class="user-info col-lg-6 col-md-6">
            Welcome <strong><u>@Model.UserName!</u></strong>
        </div>
    </header>
    <div class="row config-container">
        <div id="text-container" class="row col-lg-11 col-md-12">

            <!-- Show radio buttons for Embed types -->
            <div class="col-lg-4 col-md-12">
                <label>Choose embed type</label><br>

                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" class="custom-control-input" id="report" name="embedType" value="report" checked>
                    <label class="custom-control-label" for="report">Report</label>
                </div>

                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" class="custom-control-input" id="dashboard" name="embedType" value="dashboard">
                    <label class="custom-control-label" for="dashboard">Dashboard</label>
                </div>

                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" class="custom-control-input" id="tile" name="embedType" value="tile">
                    <label class="custom-control-label" for="tile">Tile</label>
                </div>
            </div>

            <div class="row col-lg-8 col-md-12">

                <!-- Show select list for workspace(s) -->
                <div class="row col-lg-4 col-md-12">
                    <label for="workspace-select">Choose workspace</label><br>
                    <select id="workspace-select" class="select-list col-lg-10 col-md-12">
                        <option id="workspace-default-option" value="" disabled selected>Choose workspace</option>
                    </select>
                </div>

                <!-- Show select list for report(s) -->
                <div id="report-div" class="row col-lg-4 col-md-12">
                    <label for="report-select">Choose report</label><br>
                    <select id="report-select" class="select-list col-lg-10 col-md-12" disabled>
                        <option value="" disabled selected>Choose report</option>
                    </select>
                </div>

                <!-- Show select list for dashboard(s) -->
                <div id="dashboard-div" class="row col-lg-4 col-md-12" hidden>
                    <label for="dashboard-select">Choose dashboard</label><br>
                    <select id="dashboard-select" class="select-list col-lg-10 col-md-12" disabled>
                        <option value="" disabled selected>Choose dashboard</option>
                    </select>
                </div>

                <!-- Show select list for tile(s) -->
                <div id="tile-div" class="row col-lg-4 col-md-12" hidden>
                    <label for="tile-select">Choose tile</label><br>
                    <select id="tile-select" class="select-list col-lg-10 col-md-12" disabled>
                        <option value="" disabled selected>Choose tile</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="button-container col-lg-1 col-md-12">
            <button class="embed-button" disabled>Embed</button>
        </div>
    </div>

    <!-- Show errors to the user -->
    <div id="error-container">
    </div>

    <!-- Placeholder div when Power BI report is not embedded -->
    <div class="report-wrapper col-lg-12 col-md-12 mt-12">
        <img src="~/Content/img/spinner.svg" id="report-spinner" class="spinner col-lg-12 col-md-12" alt="loader">
        <div id="report-container" class="report-container col-lg-12 col-md-12 mt-12"></div>
        <div class="report-display-text col-lg-12 col-md-12">Select workspace and report</div>
    </div>

    <!-- Placeholder div when Power BI dashboard is not embedded -->
    <div class="dashboard-wrapper col-lg-12 col-md-12 mt-12" hidden>
        <img src="~/Content/img/spinner.svg" id="dashboard-spinner" class="spinner col-lg-12 col-md-12" alt="loader">
        <div id="dashboard-container" class="dashboard-container col-lg-12 col-md-12 mt-12"></div>
        <div class="dashboard-display-text col-lg-12 col-md-12">Select workspace and dashboard</div>
    </div>

    <!-- Placeholder div when Power BI tile is not embedded -->
    <div class="tile-wrapper col-lg-12 col-md-12 mt-12" hidden>
        <img src="~/Content/img/spinner.svg" id="tile-spinner" class="spinner col-lg-12 col-md-12" alt="loader">
        <div id="tile-container" class="tile-container col-lg-12 col-md-12 mt-12"></div>
        <div class="tile-display-text col-lg-12 col-md-12">Select workspace, dashboard and tile</div>
    </div>
</div>

<script>
    loggedInUser.accessToken = "@Model.AccessToken";

    // Retrieve Power BI hostname from Web.config file
    globals.powerBiHostname = '@System.Configuration.ConfigurationManager.AppSettings["powerBiHostname"]';

    // Cache base endpoint for Power BI REST API
    globals.powerBiApi = '@System.Configuration.ConfigurationManager.AppSettings["powerBiApiUrl"]' + '/v1.0/myorg';
</script>

PowerBI-Developer-Samples/.NET Framework/Embed for your organization/UserOwnsData/Views/Shared/_Layout.cshtml
@* Copyright (c) Microsoft Corporation.
Licensed under the MIT license. *@

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Power BI Embedded sample</title>
	<link href="~/Content/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/style/style.css" rel="stylesheet" />
</head>

<body>
    <script src="~/Content/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Scripts/globals.js"></script>

    @RenderBody()

    <script src="~/Content/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/powerbi-client/dist/powerbi.min.js"></script>
    <script src="~/Scripts/error.js"></script>
    <script src="~/Scripts/data.js"></script>
    <script src="~/Scripts/embed.js"></script>
    <script src="~/Scripts/events.js"></script>
    <script src="~/Scripts/index.js"></script>
</body>
</html>